services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-dto-api
    ports:
      - "3100:3000"
    environment:
      PORT: 3000
      NODE_ENV: production
      API_KEY: itc-123
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: nestjs_dto
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: nestjs-dto-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestjs_dto
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
